version: "3.8"
services:
  authuser:
    build: .
    volumes:
      - .:/paramotor
    ports:
      - 8080:8080
    image: authuser:django
    container_name: authuser_container
    command: python manage.py runserver 0.0.0.0:8080